# NFS
nfs_ip: 192.168.1.178
nfs_export_path: /shared_data
nfs_export_options: "*(rw,sync,no_root_squash)"

# SSH
pub_key: /home/ado/.ssh/id_rsa.pub

# Users
new_user: pizzaops
new_user_password: "{{ vault_new_user_password }}"
new_user_shell: /bin/bash