# NFS
nfs_ip: 192.168.1.168
nfs_export_path: /shared_data
nfs_export_options: "*(rw,sync,no_root_squash)"

# SSH
pub_key: /home/ado/.ssh/id_rsa.pub

# Users
new_user: pizzaops
new_user_password: "{{ vault_new_user_password }}"
new_user_shell: /bin/bash

# Cron jobs
log_path: /var/log/disk_check.log

# System hardening
swappiness_value: '10'
max_file_value: '100000'

# Permissions
pizza_orders_dir: /opt/pizzeria/orders
pizza_orders_file: /opt/pizzeria/orders/active_orders.txt

# Ulimits
soft_limit_value: 4096
hard_limit_value: 8192

# LVMs
vg_name: vg_pizzeria
lv_name: lv_data
lv_size: 2g
mount_point: /mnt/pizzeria_data
fs_type: xfs