---
- name: Service Management Playbook
  hosts: pizzeria
  become: true

  tasks:

    - name: Install HTTPD
      ansible.builtin.dnf:
        name: httpd
        state: present 
      when: inventory_hostname == 'machine2'

    - name: Start and enable HTTPD service if not already started
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
      when: inventory_hostname == 'machine2'

    - name: Install bind
      ansible.builtin.dnf:
        name: bind
        state: present 
      when: inventory_hostname == 'machine3'

    - name: Start and enable bind service if not already started
      ansible.builtin.service:
        name: named
        state: started
        enabled: yes
      when: inventory_hostname == 'machine3'

    - name: Add HTML page to machine 2 only
      ansible.builtin.copy:
        src: ~/playbooks/menu.html
        dest: /var/www/html
        owner: ado
        group: ado
        mode: '0644'
      when: inventory_hostname == 'machine2'
      
        