---
- name: Service Management Playbook
  hosts: pizzeria
  become: true

  vars_files:
    - /etc/ansible/hosts

  tasks:

    - name: Install and start HTTPD
      ansible.builtin.dnf:
        name: httpd
        state: present 
      when: inventory_hostname in pizzeria['machine1']