---
- name: Service Management Playbook
  hosts: pizzeria
  become: true

  tasks:

    - name: Install and start HTTPD
      ansible.builtin.dnf:
        name: httpd
        state: present 
      when: inventory_hostname == 'machine1'

    - name: Start and enable HTTPD service if not already started
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
      when: inventory_hostname == 'machine1'