---
- name: Harden systems by reducing swappiness threshold and increasing max file size globally
  hosts: pizzeria
  become: true

  tasks:

    - name: Set vm.swappiness to 10
      ansible.posix.sysctl:
        name: vm.swappiness
        value: '10'
        sysctl_set: true
        state: present
        reload: true

    - name: Increase max file size open
      ansible.posix.sysctl:
        name: fs.file-max
        value: '100000'
        sysctl_set: true
        state: present
        reload: true