---
- name: User Management Playbook
  hosts: pizzeria
  become: true
  vars:
    pub_key: /home/ado/.ssh/id_rsa.pub
  
  vars_files:
    - vars/secrets.yml

  tasks:

    - name: Create user "pizzaops" on all servers
      ansible.builtin.user:
        name: pizzaops
        comment: Pizza Operations
        group: wheel
        shell: /bin/bash
        password: "{{ new_user_password }}"
        create_home: yes

    - name: Deploy SSH public key for keyless entry
      ansible.posix.authorized_key:
        user: pizzaops
        state: present
        key: "{{ lookup('file', '/home/ado/.ssh/id_rsa.pub') }}"

